#Spring
spring:
  profiles:
    active: pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
swagger:
  service:
    name: sharon
    description: 产品管理 - Sharon
  contact:
    name:
    url:
    email:
